<?php

function riff_base_menu() {
  $items = array();

  $items['riff'] = array(
    'title' => 'This website is being set up',
    'page callback' => 'riff_base_front',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

function riff_theme() {
  return array(
    'riff_base_front' => array(
      'variables' => array(),
    ),
  );
}

function riff_base_front() {
  return theme('riff_base_front');
}

function theme_riff_base_front($variables) {
  global $user;
  if ($user->uid != 0) {
    drupal_set_title(t('Welcome to your new Riff website'));
    $output = '<p>This is your homepage. Until you add some content to your website, you will see this message. Visitors will see a message that the site is being set up and will be ready soon.</p>';
    $output .= '<h3><strong>Get Started</strong></h3>';
    $output .= '<p>So now you have a website. Exciting! Now you need a reason for people to come here.</p>';
    $output .= l('Add a Song!', 'node/add/song', array('attributes' => array('class' => 'front-action-button')));
    $output = '<div class="front-instructions">' . $output . '</div>';
  } else {
    $output = '<p>This website is in the process of being set up. We should have something for you to look at soon!</p>';
    $output = '<div class="front-construction">' . $output . '</div>';

  }
  return $output;
}