<?php

function riff_base_menu() {
  $items = array();

  $items['riff'] = array(
    //'title' => 'This website is being set up',
    'page callback' => 'riff_base_front',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

function riff_base_permission() {
	return array(
		'view owner front page' => array(
			'title' => t('View owner front page'),
			'description' => t('View the owner version of the front page'),
		),
	);
}

function riff_base_theme($existing, $type, $theme, $path) {
  $themes = array(
    'riff_base_front' => array(
      'variables' => array(),
    ),
    'riff_base_front_default' => array(
      'variables' => array(),
    ),
    'riff_base_front_owner' => array(
      'variables' => array(),
    ),
    'riff_base_powered_by' => array(
      'variables' => array(),
    ),
  );
  if (module_exists('riff_music_content')) {
    $themes['album_node_form'] = array(
      'template' => 'album-node-form',
      'path' => drupal_get_path('module', 'riff_base') . '/templates',
      'render element' => 'form',
    );
    $themes['song_node_form'] = array(
      'template' => 'song-node-form',
      'path' => drupal_get_path('module', 'riff_base') . '/templates',
      'render element' => 'form',
    );
  }
  return $themes;
}

/**
 * Implements hook_block_info().
 */
function riff_base_block_info() {
  $blocks['powered-by'] = array(
    'info' => t('Powered by Drupal'),
    'weight' => '10',
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Generate a block with a promotional link to Drupal.org and
 * all system menu blocks.
 */
function system_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'powered-by':
      $block['subject'] = NULL;
      $block['content'] = theme('riff_base_powered_by');
      return $block;
	}
}

/* Theming and other callbacks */

function riff_base_front() {
	// Check if we have music content types set up
	if (module_exists('riff_music_content')) {
		if ($output = riff_base_front_music()) {
			return $output;
		}
	}
	if (user_access('view owner front page')) {
		return theme('riff_base_front_owner');
	}
	else {
		return theme('riff_base_front_default');
	}
}

function theme_riff_base_front_default($variables) {
	
  $select = db_select('node', 'n')
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('promote', 1)
    ->condition('status', 1)
    ->orderBy('sticky', 'DESC')
    ->orderBy('created', 'DESC')
    ->extend('PagerDefault')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access');

  $nids = $select->execute()->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build = node_view_multiple($nodes);

    // 'rss.xml' is a path, not a file, registered in node_menu().
    drupal_add_feed('rss.xml', variable_get('site_name', 'Drupal') . ' ' . t('RSS'));
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
    drupal_set_title('');
  }
	else {
    drupal_set_title(t('The @site-name is still being set up', array('@site-name' => variable_get('site_name', 'Drupal'))), PASS_THROUGH);

    $output = '<p>This website is in the process of being set up. We should have something for you to look at soon!</p>';
    $output = '<div class="front-construction">' . $output . '</div>';

    $build['default_message'] = array(
      '#markup' => $output,
      '#prefix' => '<div id="first-time">',
      '#suffix' => '</div>',
    );
  }
	return $build;
}

function theme_riff_base_front_owner($variables) {
	drupal_set_title(t('Welcome to your new Riff website'));
	$output = '<p>This is your homepage. Until you add some content to your website, you will see this message. Visitors will see a message that the site is being set up and will be ready soon.</p>';
	$output .= '<h3><strong>Get Started</strong></h3>';
	$output .= '<p>So now you have a website. Exciting! Now you need a reason for people to come here.</p>';
	$output .= l('Add a Song!', 'node/add/song', array('attributes' => array('class' => 'front-action-button')));
	$output = '<div class="front-instructions">' . $output . '</div>';
  return $output;
}

/**
 * Returns HTML for the Powered by Riff text.
 *
 * @ingroup themeable
 */
function theme_riff_base_powered_by() {
  return '<span>' . t('Powered by <a href="@poweredby">Riff</a>', array('@poweredby' => 'http://riffplatform.com')) . '</span>';
}


function riff_base_front_music() {
	$build = FALSE;
	$select = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('promote', 1)
    ->condition('status', 1)
		->condition('type', 'album')
    //->orderBy('created', 'DESC')
    ->extend('PagerDefault')
    ->limit(1)
    ->addTag('node_access');
	
	$nid = $select->execute()->fetchField();
  if (!empty($nid)) {
		$node = node_load($nid);
    $build = node_view($node, 'full');
	}
	else {
		$select = db_select('node', 'n')
			->fields('n', array('nid'))
			->condition('promote', 1)
			->condition('status', 1)
			->condition('type', 'song')
			//->orderBy('created', 'DESC')
			->extend('PagerDefault')
			->limit(1)
			->addTag('node_access');
	
		$nid = $select->execute()->fetchField();
		if (!empty($nid)) {
			$node = node_load($nid);
			$build = node_view($node, 'full');
		}
	}
	return $build;
}

function riff_base_preprocess_page($variables) {
	drupal_add_css(drupal_get_path('module', 'riff_base') . '/css/riff.css');
}

/**
 * Preprocessor for theme('album_node_form').
 */
function riff_base_preprocess_album_node_form(&$variables) {
  // nodeformcols is an alternative for this solution.
  if (!module_exists('nodeformcols')) {
    $variables['right'] = array();

    $variables['right'][] = $variables['form']['field_album_image'];
    hide($variables['form']['field_album_image']);

    // Extract the form buttons, and put them in independent variable.
    $variables['buttons'] = $variables['form']['actions'];
    hide($variables['form']['actions']);
  }
}

/**
 * Preprocessor for theme('song_node_form').
 */
function riff_base_preprocess_song_node_form(&$variables) {
  // nodeformcols is an alternative for this solution.
  if (!module_exists('nodeformcols')) {
    $variables['right'] = array();

    $variables['right'][] = $variables['form']['field_song_image'];
    hide($variables['form']['field_song_image']);

    // Extract the form buttons, and put them in independent variable.
    $variables['buttons'] = $variables['form']['actions'];
    hide($variables['form']['actions']);
  }
}

function riff_base_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node_edit_form']) && $form['#node_edit_form']) {
    $form['path']['#group'] = '';
    $form['path']['#title'] = '';
    $form['path']['#collapsible'] = FALSE;
    $form['path']['#collapsed'] = FALSE;
		$form['path']['alias']['#title'] = t('Link:');
  }
}